<a href="https://colab.research.google.com/github/Quocdank3/BTTL/blob/main/phan2cau1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# vector nhân ma trận
def vector_nhan_ma_tran(m,n):
  x=np.arange(n)
  A=np.random.rand(m,n)
  f=A.dot(x)
  print('x*A=',f)

In [ ]:
#nhân Hadamard 2 ma trận 
def nhan_hadamard_2ma_tran(m,n):
  A=np.random.rand(m,n)
  B=np.random.rand(m,n)
  f1=np.multiply(A,B)
  print('A*B=',f1)

In [ ]:
# nhân 2 ma trận 
def nhan_2_ma_tran2(m,n):
  A=np.random.rand(m,n)
  A_t=np.transpose(A)
  B=np.random.rand(m,n)
  f2=np.dot(A_t,B)
  print('A_t*B=',f2)

In [ ]:
def main():
  m=int(input('nhap m:'))
  n=int(input('nhap n:'))
  vector_nhan_ma_tran(m,n)
  nhan_hadamard_2ma_tran(m,n)
  nhan_2_ma_tran2(m,n)

In [ ]:
if __name__== '__main__':
  main()

nhap m:3
nhap n:4
x*A= [3.21168753 3.19451445 0.85045684]
A*B= [[0.07769143 0.28961569 0.47334702 0.32912581]
 [0.29911334 0.10865704 0.03052065 0.53378447]
 [0.73140084 0.20334163 0.2406795  0.76364186]]
A_t*B= [[0.6713388  0.88442275 0.23202885 0.47690124]
 [0.72046542 0.53215567 0.5674739  0.45473487]
 [0.47362838 0.3227502  0.27232289 0.35267892]
 [0.76452706 0.93007229 0.2584327  0.56315853]]
